### ISSUE TITLE
Dockerfile pip install python requirements fails

### ISSUE THREAD

**Issue by dqian3** [sunyinqi0508/AQuery2#6]
![image](https://github.com/user-attachments/assets/284d2cad-a34b-4cae-9611-a913df43a952)

There is an issue building an image from the current Dockerfile. Basically, because the latest version of Ubuntu ships with Python 3.12, Python doesn't let you install packages using the base version of pip, as shown above. To fix this, you can just add a `--break-system-packages` flag to the `pip install` line in the Dockerfile as explained in [this StackOverflow post](https://stackoverflow.com/a/76540031).

```
RUN python3 -m pip install -r AQuery2/requirements.txt --break-system-packages
```

I ran into this issue while trying to setup AQuery for the NYU Advanced Database Systems. There were some other issues as well, that I will continue to follow up with.

**Comment by sunyinqi0508** [comment]
It's now fixed. Thanks for letting me know.
